apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentalcars
  labels:
    app: rentalcars
    version: '0.1'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rentalcars
  template:
    metadata:
      name: rentalcars
      labels:
        app: rentalcars
    spec:
      containers:
        - name: rentalcars
          image: itsmaherrr/prog-dist:v0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rentalcars
  name: rentalcars
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: rentalcars
  type: LoadBalancer
status:
  loadBalancer: {}

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microservice-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"


---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rentalcars-vs
spec:
  hosts:
    - "*"
  gateways:
    - microservice-gateway
  http:
    - match:
        - uri:
            prefix: /rentalcars/
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: rentalcars