name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and test
        run: |
          export SHELL=/bin/bash
          ./gradlew build
      - name: Docker Images
        run: |
          export SHELL=/bin/bash
          docker build -t rentalservice .
          docker run -d -p 4000:8080 rentalservice
      - name: Wait for service to be ready
        run: sleep 10
      - name: Docker Logs
        run: docker logs $(docker ps -q -f ancestor=rentalservice)
      - name: Test Service
        run: curl http://localhost:4000/cars